# coding:utf-8
time_out: 200   # 设置抓取和存储一个用户资料超时时间
min_crawl_interal: 8 # 页面请求最小间隔
max_crawl_interal: 11 # 页面请求最大间隔
excp_interal: 5*60 # 请求异常的时候睡眠的时间
max_repost_page: 30  # 转发信息最多抓取多少页
max_search_page: 30 # 搜索最多抓多少页
max_retries: 5 # 抓取失败重试次数


db:
    host: 139.224.232.97
    port: 3306
    user: zhang
    password: sbblog
    db_name: weibo
    db_type: mysql

# 保存登录的cookies
redis:
    host: 127.0.0.1
    port: 6379
    password: 
    cookies: 1
    urls: 2

# celery调度的blocker和backend
brocker: redis://127.0.0.1/5
backend: redis://127.0.0.1/6